### ISSUE TITLE
Add unique task_name field to ScheduledTask object

### ISSUE THREAD

**Issue by tboulogne** [chris104957/django-carrot#79]
Hello Chris, 

Back on track after a long silence time. 
Look into your update and try it into my project. I face the same problem when i programatically create default task int my project. Each time i reload, the tasks are re-created.

With a unique ID like a a name : 
``
task_name = models.CharField(max_length=200, unique=True) #: task name with uniqueness
``
We could avoid this.

What do you think to add this ?

Thanks for your feedback.

Regards

**Comment by chris104957** [comment]
I think we can implement this for the next release. The problem we had with this previously was that adding a unique field to an existing model is a bit problematic in terms of exisitng users updating to the new version, because in past releases, users had to create their own migrations. However, carrot now ships with migrations, so we should be able to create a migration that manages this issue.

Leave it with me and I'll try and get something working for next week

**Comment by tboulogne** [comment]
thx @chris104957

**Comment by chris104957** [comment]
This is now implemented in V1.2

**Comment by tboulogne** [comment]
thx @chris104957
